
CC := clang
CPPFLAGS := -I ../../include/

.PHONY: all clean
all: list.o dlist.o sclist.o
clean:
	rm *.o

list.o: ../../include/linked_list/list.h
dlist.o: ../../include/linked_list/dlist.h
sclist.o: ../../include/linked_list/sclist.h

